// Generated by CoffeeScript 1.6.2
var SVGMINIFY, fs;

fs = require('fs');

module.exports = SVGMINIFY = (function() {
  SVGMINIFY.prototype.brunchPlugin = true;

  function SVGMINIFY(config) {
    this.config = config;
    null;
  }

  SVGMINIFY.prototype.onCompile = function(changeFiles) {
    return console.log(changeFiles);
  };

  return SVGMINIFY;

})();
