// Generated by CoffeeScript 1.6.2
var SVGMINIFY, spawn;

spawn = require('child_process').spawn;

module.exports = SVGMINIFY = (function() {
  SVGMINIFY.prototype.brunchPlugin = true;

  function SVGMINIFY(config) {
    this.config = config;
    null;
  }

  SVGMINIFY.prototype.onCompile = function(changeFiles) {
    spawn('svg/svg_minify.py', ['app', 'target/app.css', 'target/app.svg']);
    return spawn('node_modules/.bin/svgo', ['target/app.svg']);
  };

  return SVGMINIFY;

})();
